spring:
  profiles:
    include: API-KEY
  thymeleaf:
    cache: false
    check-template-location: true

chat-gpt:
  api-key:
  endpoint: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo
  temperature: 0.5
  max-tokens: 4000